name: gossa
version: git
summary: a fast and simple webserver for your files.
description: |
  a fast and simple webserver for your files, that's dependency-free and easy to review.
confinement: strict
base: core18
parts:
  gossa:
    plugin: go
    go-importpath: github.com/pldubouilh/gossa
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  gossa:
    command: gossa